import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeading } from "@/components/portal/page-heading";
import { formatMoney } from "@/lib/utils";
import { getPortalContext } from "@/lib/db/portal";

export const metadata = { title: "Invoices" };

export default async function PortalInvoicesPage() {
  const { supabase, user } = await getPortalContext();
  const { data } = await supabase.from("invoices").select("*").eq("user_id", user.id).order("created_at", { ascending: false });

  return (
    <>
      <PageHeading title="Invoices" description="Billing records synchronized from WHMCS or generated by authorized payment flows." />
      {!data?.length ? (
        <EmptyState title="No invoices" description="Invoices are not mocked. They will appear when WHMCS or billing operations create real records." />
      ) : (
        <div className="grid gap-4">
          {data.map((invoice) => (
            <Card key={invoice.id}>
              <CardContent className="flex items-center justify-between p-5">
                <div>
                  <h2 className="font-heading font-semibold">{invoice.invoice_number}</h2>
                  <p className="text-sm text-muted">{formatMoney(invoice.amount_cents, invoice.currency)}</p>
                </div>
                <Badge tone={invoice.status === "paid" ? "success" : "warning"}>{invoice.status}</Badge>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </>
  );
}
